name: fixly_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+4  # 1.0.2 — версия для юзеров, 3 — внутренний номер сборки (build number)

environment:
  sdk: '>=3.3.0 <4.0.0' # Поднял версию для совместимости с новыми пакетами

dependencies:
  flutter:
    sdk: flutter
  # UI и утилиты
  pdf: ^3.10.0
  printing: ^5.11.0
  shimmer: ^3.0.0
  google_fonts: ^8.0.1
  flutter_svg: ^2.0.10
  lucide_icons: ^0.257.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  open_file: ^3.3.0
  flutter_launcher_icons: ^0.13.1
  universal_html: ^2.2.4

  
  # Карты и геолокация
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  
  # Медиа и файлы
  image_picker: ^1.2.1
  record: ^6.2.0
  audioplayers: ^6.5.1
  path_provider: ^2.1.2
  
  # Сеть и AI
  supabase_flutter: ^2.8.0
  google_generative_ai: ^0.4.7
  http: ^1.6.0
  
  # Сервисы
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  jitsi_meet_flutter_sdk: ^11.6.0
  permission_handler: ^11.3.1
  google_sign_in: ^6.2.1 # РЕКОМЕНДУЮ эту версию, она стабильнее для Supabase
  signature: ^6.3.0
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.7
  camera: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sheber_ata.png
    - assets/sounds/11325622-atmosphere-sound-effect-239969.mp3
    - assets/sounds/dragon-studio-new-notification-3-398649.mp3
    - assets/sounds/ribhavagrawal-notification-sound-type-20-no-copyright-410276.mp3
    - assets/sounds/tutorial/
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"