// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBId47gkFpgDliIecqAmG7GK27VgSyKYik',
    appId: '1:700103731510:web:b3e287e9e8768e88a6eb97',
    messagingSenderId: '700103731510',
    projectId: 'fixly-chat',
    authDomain: 'fixly-chat.firebaseapp.com',
    storageBucket: 'fixly-chat.firebasestorage.app',
    measurementId: 'G-9DGWLBCHED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe0dYZiPz93mMBW-RcObgsUzbZuhgOqz8',
    appId: '1:700103731510:android:130be515b1e684eea6eb97',
    messagingSenderId: '700103731510',
    projectId: 'fixly-chat',
    storageBucket: 'fixly-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkEZq61DKaJngO0eY2fLiK2CAStAXjoY0',
    appId: '1:700103731510:ios:2f5af637b4d9cf88a6eb97',
    messagingSenderId: '700103731510',
    projectId: 'fixly-chat',
    storageBucket: 'fixly-chat.firebasestorage.app',
    iosBundleId: 'com.example.fixlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkEZq61DKaJngO0eY2fLiK2CAStAXjoY0',
    appId: '1:700103731510:ios:2f5af637b4d9cf88a6eb97',
    messagingSenderId: '700103731510',
    projectId: 'fixly-chat',
    storageBucket: 'fixly-chat.firebasestorage.app',
    iosBundleId: 'com.example.fixlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBId47gkFpgDliIecqAmG7GK27VgSyKYik',
    appId: '1:700103731510:web:19e959e21784684ca6eb97',
    messagingSenderId: '700103731510',
    projectId: 'fixly-chat',
    authDomain: 'fixly-chat.firebaseapp.com',
    storageBucket: 'fixly-chat.firebasestorage.app',
    measurementId: 'G-7KWN7EDTG4',
  );
}
