class AppTexts {
  static const Map<String, Map<String, String>> translations = {
    'ru': {
      'orders': 'Заявки',
      'exchange': 'Биржа',
      'masters': 'Мастера',
      'income': 'Доходы',
      'documents': 'Документы',
      'my_buildings': 'Мои дома',
      'chats': 'Чаты',
      'profile': 'Профиль',
      'analytics': 'Аналитика',
      'knowledge': 'Знания',
      'help_menu': 'Меню помощи',
      'instruction': 'Инструкция',
      'support': 'Поддержка',
      'my_profile': 'Мой Профиль',
      'buy_template': 'Купить шаблон',
      'pay_button': 'Оплатить',
      'downloading': 'Загрузка...',
      'payment_success': '✅ Оплата прошла успешно!',
      'test_payment_desc': 'Это тестовый режим оплаты. Документ будет доступен после оплаты.',
      // Выбор дома
      'new_building': 'Новый дом',
      'cancel': 'Отмена',
      'create': 'Создать',
      'osi_name': 'Название ОСИ/КСК',
      'apartments_count': 'Кол-во квартир',
      'building_attached': 'Дом привязан!',
      'attachment_error': 'Ошибка привязки к дому',
      'creation_error': 'Ошибка создания дома',
      'my_home': 'Мой дом',
      'search_or_create_home': 'Найдите свой дом по адресу или создайте новый, если его ещё нет в Fixly.',
      'change_home': 'Сменить дом',
      'select_or_create_home': 'Выбрать / создать дом',
      'current_home': 'Текущий дом',
      'verified': 'Подтверждено',
      'pending_verification': 'Ожидает подтверждения',
      // Объявления
      'announcements': 'Объявления',
      'new_announcement': 'Новое объявление',
      'announcement_title': 'Заголовок *',
      'announcement_text': 'Текст...',
      'urgent': 'Срочное',
      'urgent_label': 'СРОЧНО',
      'publish': 'Опубликовать',
      'search': 'Поиск...',
      'no_announcements': 'Объявлений нет',
      'delete': 'Удалить',
      'delete_confirm': 'Удалить?',
      'no': 'Нет',
      // Голосования
      'votings': 'Голосования',
      'create_voting': 'Создать голосование',
      'new_voting': 'Новое голосование',
      'no_votings': 'По этому фильтру голосований нет',
      'no_title': 'Без названия',
      'until': 'до',
      'filter_active': 'Активные',
      'filter_draft': 'Черновики',
      'filter_closed': 'Закрытые',
      'filter_all': 'Все',
      'status_active': 'Активно',
      'status_draft': 'Черновик',
      'status_closed': 'Закрыто',
      'status_archived': 'Архив',
      'voting_question': 'Вопрос',
      'voting_description': 'Описание',
      'voting_days': 'Срок, дней',
      // Детали голосования
      'current_question': 'ТЕКУЩИЙ ВОПРОС',
      'live_stats': 'LIVE СТАТИСТИКА',
      'vote_yes': 'ЗА',
      'vote_no': 'ПРОТИВ',
      'vote_abstain': 'ВОЗД.',
      'already_voted': 'Вы уже проголосовали',
      'vote_as_resident': 'Проголосовать как житель',
      'download_protocol': 'СКАЧАТЬ АРХИВ / ПРОТОКОЛ',
      'voted_percentage': 'Проголосовало {percent}% квартир',
      'your_signature': 'ВАША ПОДПИСЬ',
      'send_vote': 'ОТПРАВИТЬ ГОЛОС',
      'select_and_sign': 'Выберите вариант и подпишите',
      'vote_success': 'Голос засчитан!',
      // Профиль
      'edit_field': 'Изменить {field}',
      'enter_field': 'Введите {field}',
      'save': 'Сохранить',
      'data_updated': 'Данные обновлены',
      'save_error': 'Ошибка сохранения',
      'photo_updated': 'Фото профиля обновлено',
      'photo_error': 'Не удалось загрузить фото',
      'not_specified': 'Не указан',
      'tap_to_enter': 'Нажмите для ввода',
      'online': 'В СЕТИ',
      'busy': 'ЗАНЯТ',
      'address_data': 'АДРЕСНЫЕ ДАННЫЕ',
      'profile_data': 'ДАННЫЕ ПРОФИЛЯ',
      'select_home_map': 'Выбрать дом на карте',
      'confirm_home': 'Подтвердите свой дом или выберите другой',
      'osi_jk_name': 'Название ОСИ / ЖК',
      'bin_iin': 'БИН / ИИН',
      'verification': 'Верификация',
      'confirm_profile': 'Подтвердите профиль',
      'city': 'Город',
      'street_house': 'Улица и дом',
      'apartment': 'Квартира',
      'your_works': 'ВАШИ РАБОТЫ',
      'add': 'Добавить',
      'no_photos': 'Фото еще не добавлены',
      'role_chairman': 'Председатель ОСИ',
      'role_resident': 'Житель',
      'role_master': 'Мастер',
      'rating': 'Рейтинг',
      'orders_count': 'Заявки',
      'experience': 'Опыт',
      // Ошибки
      'error_network': 'Нет подключения к интернету. Проверьте сеть.',
      'error_auth': 'Нет прав доступа. Войдите заново.',
      'error_server': 'Ошибка сервера. Попробуйте позже.',
      'error_unknown': 'Что-то пошло не так. Попробуйте ещё раз.',
      'retry': 'Повторить',
    },
    'kk': {
      'orders': 'Өтінімдер',
      'exchange': 'Биржа',
      'masters': 'Шеберлер',
      'income': 'Табыстар',
      'documents': 'құжаттары',
      'my_buildings': 'Менің үйлерім',
      'chats': 'Чаттар',
      'profile': 'Профиль',
      'analytics': 'Аналитика',
      'knowledge': 'Білім',
      'help_menu': 'Көмек мәзірі',
      'instruction': 'Нұсқаулық',
      'support': 'Қолдау',
      'my_profile': 'Менің Профилім',
      'buy_template': 'Үлгіні сатып алу',
      'pay_button': 'Төлеу',
      'downloading': 'Жүктелуде...',
      'payment_success': '✅ Төлем сәтті өтті!',
      'test_payment_desc': 'Бұл тесттік төлем режимі. Құжат төлемнен кейін қолжетімді болады.',
      // Выбор дома
      'new_building': 'Жаңа үй',
      'cancel': 'Бас тарту',
      'create': 'Жасау',
      'osi_name': 'МТБ/ТКШ атауы',
      'apartments_count': 'Пәтер саны',
      'building_attached': 'Үй тіркелді!',
      'attachment_error': 'Үйге тіркеу қатесі',
      'creation_error': 'Үй жасау қатесі',
      'my_home': 'Менің үйім',
      'search_or_create_home': 'Мекенжай бойынша үйіңізді табыңыз немесе Fixly-де жоқ болса, жаңасын жасаңыз.',
      'change_home': 'Үйді ауыстыру',
      'select_or_create_home': 'Үй таңдау / жасау',
      'current_home': 'Ағымдағы үй',
      'verified': 'Расталды',
      'pending_verification': 'Расталуды күтуде',
      // Объявления
      'announcements': 'Хабарландырулар',
      'new_announcement': 'Жаңа хабарландыру',
      'announcement_title': 'Тақырып *',
      'announcement_text': 'Мәтін...',
      'urgent': 'Шұғыл',
      'urgent_label': 'ШҰҒЫЛ',
      'publish': 'Жариялау',
      'search': 'Іздеу...',
      'no_announcements': 'Хабарландырулар жоқ',
      'delete': 'Өшіру',
      'delete_confirm': 'Өшіру?',
      'no': 'Жоқ',
      // Голосования
      'votings': 'Дауыс беру',
      'create_voting': 'Дауыс жасау',
      'new_voting': 'Жаңа дауыс',
      'no_votings': 'Бұл сүзгі бойынша дауыс жоқ',
      'no_title': 'Атаусыз',
      'until': 'дейін',
      'filter_active': 'Белсенді',
      'filter_draft': 'Жоба',
      'filter_closed': 'Жабық',
      'filter_all': 'Бәрі',
      'status_active': 'Белсенді',
      'status_draft': 'Жоба',
      'status_closed': 'Жабық',
      'status_archived': 'Мұрағат',
      'voting_question': 'Сұрақ',
      'voting_description': 'Сипаттама',
      'voting_days': 'Мерзімі, күн',
      // Детали голосования
      'current_question': 'АҒЫМДАҒЫ СҰРАҚ',
      'live_stats': 'LIVE СТАТИСТИКА',
      'vote_yes': 'ҚОЛДАЙМЫН',
      'vote_no': 'ҚАРСЫМЫН',
      'vote_abstain': 'ҚАЛЫС ПЕН',
      'already_voted': 'Сіз дауыс беріп қойдыңыз',
      'vote_as_resident': 'Тұрғын ретінде дауыс беру',
      'download_protocol': 'АРХИВ / ХАТТАМАНЫ ЖҮКТЕУ',
      'voted_percentage': 'Пәтерлердің {percent}% дауыс берді',
      'your_signature': 'СІЗДІҢ ҚОЛЫҢЫЗ',
      'send_vote': 'ДАУЫСТЫ ЖІБЕРУ',
      'select_and_sign': 'Нұсқаны таңдап, қол қойыңыз',
      'vote_success': 'Дауыс қабылданды!',
      // Профиль
      'edit_field': '{field} өзгерту',
      'enter_field': '{field} енгізіңіз',
      'save': 'Сақтау',
      'data_updated': 'Деректер жаңартылды',
      'save_error': 'Сақтау қатесі',
      'photo_updated': 'Профиль фотосы жаңартылды',
      'photo_error': 'Фото жүктелмеді',
      'not_specified': 'Көрсетілмеген',
      'tap_to_enter': 'Енгізу үшін басыңыз',
      'online': 'ЖЕЛІДЕ',
      'busy': 'БОС ЕМЕС',
      'address_data': 'МЕКЕН-ЖАЙ МӘЛІМЕТТЕРІ',
      'profile_data': 'ПРОФИЛЬ ДЕРЕКТЕРІ',
      'select_home_map': 'Картадан үйді таңдау',
      'confirm_home': 'Үйіңізді растаңыз немесе басқа үйді таңдаңыз',
      'osi_jk_name': 'ОСИ / ТҮК атауы',
      'bin_iin': 'БСН / ЖСН',
      'verification': 'Верификация',
      'confirm_profile': 'Профильді растаңыз',
      'city': 'Қала',
      'street_house': 'Көше мен үй',
      'apartment': 'Пәтер',
      'your_works': 'ЖҰМЫСТАРЫҢЫЗ',
      'add': 'Қосу',
      'no_photos': 'Фотолар жоқ',
      'role_chairman': 'ОСИ төрағасы',
      'role_resident': 'Тұрғын',
      'role_master': 'Шебер',
      'rating': 'Рейтинг',
      'orders_count': 'Тапсырыс',
      'experience': 'Тәжірибе',
      // Ошибки
      'error_network': 'Интернет жоқ. Желіні тексеріңіз.',
      'error_auth': 'Қатынау құқы жоқ. Қайтадан кіріңіз.',
      'error_server': 'Сервер қатесі. Кейінірек әрекет қәріңіз.',
      'error_unknown': 'Бірдеңе қате орын алды. Қайталаңыз.',
      'retry': 'Қайталау',
    },
  };

  static String get(String key, String lang) {
    String shortLang = lang.length >= 2 ? lang.substring(0, 2).toLowerCase() : 'ru';
    return translations[shortLang]?[key] ?? translations['ru']![key] ?? key;
  }
}